name: CI
on: pull_request

jobs:
  ci:
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.9", "3.10"]
        poetry-version: ["1.1.11"]
        os: [ubuntu-20.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: poetry install
      - name: Missing updates
        run: |
          # Are there any changes we forgot to commit?
          make all
          if ! [[ -z "$(git status --porcelain)" ]]; then
            echo "Be sure to run 'make all' and commit changes." && exit 1;
          fi
      - name: Lint
        run: make lint
      - name: test
        run: make test

